services:
  - type: web
    name: music-stream-backend
    runtime: node
    buildCommand: |
      mkdir -p bin
      curl -fsSL https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o bin/yt-dlp
      chmod a+rx bin/yt-dlp
      npm install
      npm run build
      # Install Node.js as JS runtime for yt-dlp
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000