#!/usr/bin/env python3
"""
YouTube Cookie Refresher
Maintains a persistent browser session and exports cookies in Netscape format.
Designed to run headlessly in CI/CD (GitHub Actions) or locally.
"""

import os
import json
import time
import sys
import argparse
from pathlib import Path
from datetime import datetime

# pip install playwright
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout

# ─── Config ────────────────────────────────────────────────────────────────────
SESSION_DIR   = Path(os.environ.get("YT_SESSION_DIR", "./yt_session"))
OUTPUT_FILE   = Path(os.environ.get("COOKIES_OUTPUT", "./cookies.txt"))
PROXY_SERVER  = os.environ.get("YT_PROXY", "")          # e.g. "http://user:pass@host:port"
HEADLESS      = os.environ.get("HEADLESS", "true").lower() == "true"
YT_URL        = "https://www.youtube.com"
LOGIN_URL     = "https://accounts.google.com/signin/v2/identifier?service=youtube"
# ────────────────────────────────────────────────────────────────────────────────


def log(msg: str):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def to_netscape(cookies: list[dict]) -> str:
    """Convert Playwright cookie dicts → Netscape HTTP Cookie File format."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by refresh_cookies.py", ""]
    for c in cookies:
        domain      = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path        = c.get("path", "/")
        secure      = "TRUE" if c.get("secure", False) else "FALSE"
        expires     = str(int(c.get("expires", 0)))
        name        = c.get("name", "")
        value       = c.get("value", "")
        # Skip session-only cookies (expires = -1 or 0) — they won't survive
        if int(float(expires)) <= 0:
            continue
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def is_logged_in(page) -> bool:
    """Check if the current session is authenticated."""
    try:
        page.goto(YT_URL, wait_until="domcontentloaded", timeout=20_000)
        # Logged-in YouTube shows an avatar button; logged-out shows "Sign in"
        sign_in = page.query_selector('a[href*="accounts.google.com/ServiceLogin"]')
        avatar  = page.query_selector('button#avatar-btn')
        return avatar is not None and sign_in is None
    except PlaywrightTimeout:
        log("Timed out checking login state.")
        return False


def save_cookies(context, path: Path):
    cookies = context.cookies()
    yt_cookies = [c for c in cookies if "youtube.com" in c.get("domain", "")
                  or "google.com" in c.get("domain", "")]
    if not yt_cookies:
        log("WARNING: No YouTube/Google cookies found — session may be invalid.")
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_netscape(yt_cookies))
    log(f"Saved {len(yt_cookies)} cookies → {path}")
    return True


def load_storage_state(context):
    """Load saved auth state if it exists (faster than full cookie reload)."""
    state_file = SESSION_DIR / "auth_state.json"
    if state_file.exists():
        try:
            state = json.loads(state_file.read_text())
            context.add_cookies(state.get("cookies", []))
            log("Loaded saved auth state.")
            return True
        except Exception as e:
            log(f"Could not load auth state: {e}")
    return False


def save_storage_state(context):
    state_file = SESSION_DIR / "auth_state.json"
    SESSION_DIR.mkdir(parents=True, exist_ok=True)
    cookies = context.cookies()
    state_file.write_text(json.dumps({"cookies": cookies}, indent=2))
    log(f"Saved auth state → {state_file}")


def interactive_login(page, context):
    """
    Opens a visible browser for the user to log in manually.
    Used for first-time setup only.
    """
    log("─" * 60)
    log("FIRST-TIME SETUP: Manual login required.")
    log("A browser window will open. Log into YouTube/Google.")
    log("After logging in, press ENTER here to save your session.")
    log("─" * 60)

    page.goto(YT_URL)
    input("\nPress ENTER after you have logged in successfully... ")

    # Verify
    if is_logged_in(page):
        log("Login confirmed!")
        save_storage_state(context)
        return True
    else:
        log("ERROR: Could not verify login. Please try again.")
        return False


def refresh(headless=True, force_login=False):
    proxy_config = {"server": PROXY_SERVER} if PROXY_SERVER else None

    with sync_playwright() as p:
        # Use persistent context so Playwright stores browser profile on disk
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(SESSION_DIR),
            headless=headless,
            proxy=proxy_config,
            viewport={"width": 1280, "height": 800},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            args=[
                "--no-sandbox",
                "--disable-blink-features=AutomationControlled",
                "--disable-dev-shm-usage",
            ],
            ignore_default_args=["--enable-automation"],
        )

        page = context.new_page()

        # Remove webdriver fingerprint
        page.add_init_script("""
            Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
        """)

        # ── Check existing session ──────────────────────────────────────────
        if not force_login and SESSION_DIR.exists():
            log("Checking existing session...")
            if is_logged_in(page):
                log("Session is valid. Exporting cookies...")
                ok = save_cookies(context, OUTPUT_FILE)
                context.close()
                return ok
            else:
                log("Session expired or not found.")

        # ── Need to (re-)login ──────────────────────────────────────────────
        if headless:
            log("ERROR: Session invalid and running headless. Cannot login.")
            log("Run locally first: python refresh_cookies.py --setup")
            context.close()
            return False

        # Interactive login
        ok = interactive_login(page, context)
        if ok:
            time.sleep(2)  # let cookies settle
            save_cookies(context, OUTPUT_FILE)

        context.close()
        return ok


def main():
    parser = argparse.ArgumentParser(description="YouTube Cookie Refresher")
    parser.add_argument(
        "--setup",
        action="store_true",
        help="First-time setup: open browser for manual login",
    )
    parser.add_argument(
        "--force-login",
        action="store_true",
        help="Force a new login even if session exists",
    )
    args = parser.parse_args()

    if args.setup:
        log("Running first-time setup (headful mode)...")
        success = refresh(headless=False, force_login=True)
    else:
        success = refresh(headless=HEADLESS, force_login=args.force_login)

    if not success:
        log("Cookie refresh FAILED.")
        sys.exit(1)

    log("Cookie refresh complete.")
    sys.exit(0)


if __name__ == "__main__":
    main()
