#!/usr/bin/env python3
"""
YouTube Cookie Refresher
Injects stored cookies into a fresh browser, refreshes them via YouTube visit,
then exports in Netscape format for yt-dlp.
"""

import os
import json
import sys
from pathlib import Path
from datetime import datetime

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeout

# ─── Config ────────────────────────────────────────────────────────────────────
SESSION_DIR     = Path(os.environ.get("YT_SESSION_DIR", "./yt_session"))
OUTPUT_FILE     = Path(os.environ.get("COOKIES_OUTPUT", "./cookies.txt"))
COOKIES_JSON_IN = os.environ.get("YT_COOKIES_JSON", "")   # raw JSON string from secret
PROXY_SERVER    = os.environ.get("YT_PROXY", "")
HEADLESS        = os.environ.get("HEADLESS", "true").lower() == "true"
YT_URL          = "https://www.youtube.com"
# ────────────────────────────────────────────────────────────────────────────────


def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def to_netscape(cookies):
    lines = ["# Netscape HTTP Cookie File", "# Generated by refresh_cookies.py", ""]
    for c in cookies:
        domain      = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path        = c.get("path", "/")
        secure      = "TRUE" if c.get("secure", False) else "FALSE"
        expires     = str(int(float(c.get("expires", 0))))
        name        = c.get("name", "")
        value       = c.get("value", "")
        if int(float(expires)) <= 0:
            continue
        lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def run_headless():
    if not COOKIES_JSON_IN:
        log("ERROR: YT_COOKIES_JSON env var is empty. Secret not set?")
        return False

    try:
        stored_cookies = json.loads(COOKIES_JSON_IN)
    except json.JSONDecodeError as e:
        log(f"ERROR: Could not parse YT_COOKIES_JSON: {e}")
        return False

    log(f"Loaded {len(stored_cookies)} cookies from secret.")
    proxy_config = {"server": PROXY_SERVER} if PROXY_SERVER else None

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=True,
            proxy=proxy_config,
            args=[
                "--no-sandbox",
                "--disable-blink-features=AutomationControlled",
                "--disable-dev-shm-usage",
            ],
        )
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
        )

        context.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', { get: () => undefined });"
        )

        try:
            context.add_cookies(stored_cookies)
            log("Cookies injected into browser.")
        except Exception as e:
            log(f"ERROR injecting cookies: {e}")
            browser.close()
            return False

        page = context.new_page()
        try:
            log("Visiting YouTube...")
            page.goto(YT_URL, wait_until="domcontentloaded", timeout=30_000)
            page.wait_for_timeout(3000)
        except PlaywrightTimeout:
            log("WARNING: YouTube visit timed out — exporting whatever cookies we have.")

        avatar = page.query_selector("button#avatar-btn")
        sign_in = page.query_selector('a[href*="accounts.google.com/ServiceLogin"]')
        if avatar and not sign_in:
            log("Login confirmed — session is valid.")
        else:
            log("WARNING: Could not confirm login. Cookies may be expired.")

        all_cookies = context.cookies()
        yt_cookies = [
            c for c in all_cookies
            if "youtube.com" in c.get("domain", "") or "google.com" in c.get("domain", "")
        ]

        if not yt_cookies:
            log("ERROR: No YouTube/Google cookies found after injection.")
            browser.close()
            return False

        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_FILE.write_text(to_netscape(yt_cookies))
        log(f"Exported {len(yt_cookies)} cookies -> {OUTPUT_FILE}")

        # Save refreshed cookies for the workflow to re-upload as secret
        refreshed_path = Path("/tmp/yt_cookies_refreshed.json")
        refreshed_path.write_text(json.dumps(yt_cookies, indent=2))
        log(f"Saved refreshed cookies JSON -> {refreshed_path}")

        browser.close()
        return True


def run_setup():
    log("=" * 60)
    log("FIRST-TIME SETUP: Manual login required.")
    log("A browser window will open. Log into YouTube.")
    log("Come back here and press ENTER once logged in.")
    log("=" * 60)

    proxy_config = {"server": PROXY_SERVER} if PROXY_SERVER else None

    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            user_data_dir=str(SESSION_DIR),
            headless=False,
            proxy=proxy_config,
            viewport={"width": 1280, "height": 800},
            args=["--disable-blink-features=AutomationControlled"],
            ignore_default_args=["--enable-automation"],
        )

        page = context.new_page()
        page.goto(YT_URL)

        input("\nPress ENTER after you have logged in to YouTube... ")

        cookies = context.cookies()
        yt_cookies = [
            c for c in cookies
            if "youtube.com" in c.get("domain", "") or "google.com" in c.get("domain", "")
        ]

        log(f"Found {len(yt_cookies)} YouTube/Google cookies.")

        OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_FILE.write_text(to_netscape(yt_cookies))
        log(f"Saved cookies.txt -> {OUTPUT_FILE}")

        json_path = Path("/tmp/yt_cookies.json")
        json_path.write_text(json.dumps(yt_cookies, indent=2))
        log(f"Saved cookies JSON -> {json_path} ({len(json_path.read_text())} chars)")
        log("")
        log("Now upload to GitHub:")
        log("  gh secret set YT_COOKIES_JSON --repo YOUR/REPO < /tmp/yt_cookies.json")

        context.close()
        return True


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--setup", action="store_true", help="First-time local login setup")
    args = parser.parse_args()

    success = run_setup() if args.setup else run_headless()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()